# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170423_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='position',
        ),
        migrations.RemoveField(
            model_name='response',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
