# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170423_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='workShift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShiftPosition', related_query_name='ShiftPosition', to='jobs.WorkShift'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobShift', related_query_name='JobShift', to='jobs.Job'),
        ),
    ]
