# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_auto_20170423_2123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Reviewing'), (2, 'Offer'), (3, 'Available'), (4, 'Unavailable'), (5, 'Cancelled')], default=1)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Response_Position', related_query_name='Response_Position', to='jobs.Position')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='StaffResponse', related_query_name='StaffResponse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
