# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResponsePosition', related_query_name='ResponsePosition', to='jobs.Position'),
        ),
    ]
